# Generated by Django 2.2.5 on 2022-02-26 04:26

from django.db import migrations, models
import fashflix.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('path', models.FilePathField(path=fashflix.models.catalog_path)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='$', max_length=1)),
                ('price', models.FloatField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
