# Generated by Django 2.2.5 on 2022-03-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashflix', 'debug_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preference_vector',
            field=models.TextField(blank=True, default='null', null=True),
        ),
    ]
