# Generated by Django 2.2.5 on 2022-02-26 04:55

from django.db import migrations, models
import fashflix.models


class Migration(migrations.Migration):

    dependencies = [
        ('fashflix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputimage',
            name='path',
            field=models.FilePathField(blank=True, match='foo.*', null=True, path=fashflix.models.catalog_path, recursive=True),
        ),
    ]
