name: cs329s_project
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch
  - torchvision
  - tqdm
  - pip:
    - findspark
    - numpy
    - pandas
    - pillow
    - streamlit
